apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy
  namespace: monitoring
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`alloy.edgesoft.local`)
    services:
    - name: monitoring-grafana-alloy
      port: 12345